config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}

  #diary
  get '/diary/index_post' => 'diary#index_post', as: 'index_posts'
  get '/diary/new_post' => 'diary#new_post', as: 'new_post'
  get '/diary/show_post/:id' => 'diary#show_post', as: 'show_post'
  post '/diary/create_post' => 'diary#create_post'
  get '/diary/edit_post/:id' => 'diary#edit_post'
  patch '/diary/update_post' => 'diary#update_post'
  delete '/diary/destroy_post/:id' => 'diary#destroy_post'
  get '/diary/pick_date' => 'diary#pick_date'

  #search
  get 'diary/search' => 'search#result', as: 'diary_search'

  #recommendation
  get '/recommend/result' => 'recommend#result', as:'recommend_result'

  #my page
  get '/mypage/index' => 'mypage#index', as: 'index_mypage'
  get '/mypage/category' => 'mypage#category', as: 'category'

  #lookbook
  get '/lookbook/index' => 'lookbook#index', as: 'index_lookbook'
  get '/lookbook/like/:id' => 'lookbook#likes', as: 'like_lookbook'

  root 'home#index'
end

app/controllers/diary_controller.rb
class DiaryController < ApplicationController
  before_action :set_post, except: %i[pick_date index_post new_post create_post update_post]

  def index_post
    if params[:picked_date].present?
      @picked_date = params[:picked_date]
    else
      @picked_date = Date.today.strftime('%Y-%m-%d')
    end

    @my_posts = Post.index(current_user)
    @target_posts = @my_posts.where(posted_at: @picked_date)
  end

  def show_post
    Post.show_post(@post)
  end

  def new_post
    @post = Post.new_post
    @picked_date = params[:picked_date]
  end

  def create_post
    # 날씨정보 받아오기
    weather = get_current_weather

    # post params
    post_params = params[:post]
    post_id = Post.create_post(post_params)

    # codi params
    codi_params = {}
    codi_params.merge!(post_id: post_id)
    codi_params.merge!(weather: weather)
    codi_params.merge!(event: params[:event])
    codi_params.merge!(preference: params[:preference])
    codi_id = Codi.create_codi(codi_params)

    # clothes params
    clothes_info = JSON.parse(params['clothes_info'])
    clothes_info.each do |cloth_info|
      cloth_params = {}
      cloth_params[:codi_id] = codi_id
      cloth_params[:main_category] = cloth_info['main']
      cloth_params[:sub_category] = cloth_info['sub']
      cloth_params[:color] = cloth_info['color']

      Cloth.create_cloth(cloth_params)
    end

    redirect_to root_path
  end

  def edit_post
    Post.edit_post(@post)
    @picked_date = @post.posted_at
  end

  def update_post
    target = Post.where(posted_at: params[:post][:posted_at]).first
    #Post.update_post(target, params[:post])
    target.title = params[:post][:title]
    target.body = params[:post][:body]
    target.image = params[:post][:image]
    target.posted_at = params[:post][:posted_at]
    target.save
    redirect_to root_path
  end

  def destroy_post
    Post.destroy_post(@post)
    redirect_to root_path
  end

  def pick_date
    @picked_date = params[:picked_date]
    my_posts = Post.index(current_user)
    @target_posts = my_posts.where(posted_at: @picked_date)
    # redirect_to index_posts_path(picked_date: @picked_date)
    respond_to do |format|
      format.js {}
    end
  end

  private

  def global_var
    if params[:picked_date].present?
      @picked_date = params[:picked_date]
    else
      @picked_date = Date.today.strftime('%Y-%m-%d')
    end

    @my_posts = Post.index(current_user)
    @target_posts = @my_posts.where(posted_at: @picked_date)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def get_current_weather
    response = HTTParty.get('http://api.openweathermap.org/data/2.5/weather?id=524901&APPID=9470ef016a30a1dd8fe2e39a52be2097&q=seoul&units=metric', headers: { 'APPID' => '9470ef016a30a1dd8fe2e39a52be2097' }).parsed_response
    if response['main']
      return response['main']
    else
      return false
    end
  end
end

app/helpers/diary_helper.rb
module DiaryHelper
end

app/views/diary/_post_form.html.erb
<div class="block">
  <div class="block-title"><%= picked_date.strftime("%Y년 %m월 %d일") %> OOTD 다이어리 작성</div>
  <div class="list inline-labels no-hairlines-md">
    <%= form_for @post, url: '/diary/create_post' do |f| %>
      <%= f.hidden_field :user_id,value: current_user.id %>
      <%= f.hidden_field :posted_at,value: picked_date %>
      <% if @post.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <ul>
        <li class="item-content item-input">
          <div class="row" style="width:100%;">
            <div class="item-inner col">
              <div class="item-title item-label" style="font-size:0.7em;color:grey;">공개범위</div>
              <div class="item-input-wrap">
                <%= f.select(:open_range, options_for_select([['전체공개','전체공개'], ['나만보기','나만보기']]), value:'전체공개' ) %>
              </div>
            </div>
            <div class="item-inner col">
              <div class="item-title item-label" style="font-size:0.7em;color:grey;">이벤트</div>
              <div class="item-input-wrap">
                <%= select_tag(:event, options_for_select([['비즈니스','비즈니스'], ['데이트','데이트'], ['친구약속','친구약속'], ['데일리','데일리']]), value:'비즈니스' ) %>
              </div>
            </div>
          </div>
        </li>
        <li class="item-content item-input">
          <div class="item-inner">
            <div class="item-input-wrap">
              <img id="image_upload" src="#" />
              <!-- <input type='file' onchange="readURL(this);" /> -->
              <%= f.file_field :image %> <!--name => post[image] -->
            </div>
          </div>
        </li>
        <li class="item-content item-input">
          <div class="item-inner">
            <div class="item-input-wrap">
              <%= f.text_field :title, placeholder:"제목" %>
              <span class="input-clear-button"></span>
            </div>
          </div>
        </li>
        <li class="item-content item-input">
          <div class="item-inner">
            <div class="item-input-wrap">
              <%= f.text_area :body, placeholder:"내용" %>
              <span class="input-clear-button"></span>
            </div>
          </div>
        </li>
        <li class="item-content item-input">
          <div class="item-inner">
            <div class="item-title item-label">선호 점수</div>
            <div class="item-input-wrap">
              <div class="range-slider range-slider-init" data-label="true">
                <input type="range" name="preference" value="5" min="1" max="5" step="1">
              </div>
            </div>
          </div>
        </li>
        <div class="block">
          <%= f.submit class:"button button-fill color-blue" %>
        </div>
      </ul>
    <% end %>
  </div>
</div>

app/views/diary/_post_list.html.erb
<ul>
  <% target_posts.each do |post| %>
    <li>
      <a href="/diary/show_post/<%= post.id %>" class="item-link item-content">
        <div class="item-inner">
          <div class="item-title-row">
            <div class="item-title"><%= post.title %></div>
            <div class="item-after"></div>
          </div>
          <div class="item-subtitle post-date"><%= post.posted_at.strftime("%Y년 %m월 %d일") %></div>
          <div class="item-text"><%= post.body %></div>
        </div>
      </a>
    </li>
  <% end %>
</ul>

app/views/diary/edit_post.html.erb
<div class="navbar no-shadow">
  <div class="navbar-inner sliding">
    <div class="left">
      <a href="#" class="link back">
        <i class="icon icon-back"></i>
        <span class="ios-only">Back</span>
      </a>
    </div>
    <div class="title">글 수정</div>
  </div>
</div>

<div class="page-content">
  <div class="block">
    <div class="block-title"><%= @picked_date %> 다이어리 작성</div>
    <div class="list inline-labels no-hairlines-md">
      <%= form_for @post, url: "/diary/update_post" do |f| %>
        <%= f.hidden_field :user_id,value: current_user.id %>
        <%= f.hidden_field :posted_at,value: @picked_date %>

        <!-- 옷 정보 -->
        <%= hidden_field_tag :clothes_info, value: "" %>

        <% if @post.errors.any? %>
          <div id="errorExplanation">
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
            <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <ul>
          <li class="item-content item-input">
            <div class="row" style="width:100%;">
              <div class="item-inner col">
                <div class="item-title item-label" style="font-size:0.7em;color:grey;">공개범위</div>
                <div class="item-input-wrap">
                  <%= f.select(:open_range, options_for_select([['전체공개','전체공개'], ['나만보기','나만보기']]), value:'전체공개' ) %>
                </div>
              </div>
              <div class="item-inner col">
                <div class="item-title item-label" style="font-size:0.7em;color:grey;">이벤트</div>
                <div class="item-input-wrap">
                  <%= select_tag(:event, options_for_select([['비즈니스','비즈니스'], ['데이트','데이트'], ['친구약속','친구약속'], ['데일리','데일리']]), value:'비즈니스' ) %>
                </div>
              </div>
            </div>
          </li>
          <li class="item-content item-input">
            <div class="item-inner">
              <div class="item-input-wrap">
                <img id="image_upload" src="#" />
                <!-- <input type='file' onchange="readURL(this);" /> -->
                <%= f.file_field :image %>
              </div>
            </div>
          </li>
          <li class="item-content item-input">
            <div class="item-inner">
              <div class="item-input-wrap">
                <%= f.text_field :title, placeholder:"제목" %>
                <span class="input-clear-button"></span>
              </div>
            </div>
          </li>
          <li class="item-content item-input">
            <div class="item-inner">
              <div class="item-input-wrap">
                <%= f.text_area :body, placeholder:"내용" %>
                <span class="input-clear-button"></span>
              </div>
            </div>
          </li>
          <div class="list links-list" style="margin:0 auto;" >
            <ul style="padding-left:0px;">
              <li class="item-content item-input">
                <div class="item-inner">
                  <div class="item-input-wrap">
                    <a class="link popup-open" style="padding-left:0px;" href="#" data-popup=".popup-about">Category</a>
                  </div>
                </div>
              </li>
            </ul>
          </div>
          <div class="popup popup-about">
            <div class="block">
              <a class="button button-fill color-blue link popup-close" id="category_select_btn" href="#">선택완료</a>
              <div class="block-title">Category</div>
              <div class="list accordion-list">
                <ul>
                  <% Cloth.get_clothes_info.each do |key, value| %>
                    <li class="accordion-item">
                      <a href="#" class="item-content item-link">
                        <div class="item-inner">
                          <div class="item-title"><%= key %></div>
                        </div>
                      </a>
                      <div class="accordion-item-content">
                        <div class="block">
                          <div class="list">
                            <ul>
                              <% value.each do |cloth_name| %>
                                <li>
                                  <label class="item-radio item-content">
                                    <input type="radio" name="demo-radio" value="<%= key %>_<%= cloth_name %>" /> <!-- checked="checked"/> -->
                                    <i class="icon icon-radio"></i>
                                    <div class="item-inner">
                                      <div class="item-title"><%= cloth_name %></div>
                                    </div>
                                  </label>
                                </li>
                              <% end %>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
          <li class="item-content item-input">
            <div class="item-inner">
              <div class="item-title item-label">Preference</div>
              <div class="item-input-wrap">
                <div class="range-slider range-slider-init" data-label="true">
                  <input type="range" name="preference" value="5" min="1" max="5" step="1">
                </div>
              </div>
            </div>
          </li>
          <div class="block">
            <%= f.submit class:"button button-fill color-blue" %>
          </div>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/diary/index_post.html.erb
<div class="navbar no-shadow">
  <div class="navbar-inner">
    <div class="left">
      <a href="#" class="link back">
        <i class="icon icon-back"></i>
        <span class="ios-only">Back</span>
      </a>
    </div>
    <div class="title"></div>
    <div class="right">
      <!-- <a class="link icon-only searchbar-enable" data-searchbar=".searchbar-components">
        <i class="icon f7-icons ios-only">search_strong</i>
        <i class="icon material-icons md-only">search</i>
      </a> -->
    </div>
    <%# form_for "",url: result_path, role:"search", method: :get, class: "searchbar searchbar-expandable searchbar-components searchbar-init" do %>
    <!-- <form data-search-container=".components-list" data-search-in="a" class="searchbar searchbar-expandable searchbar-components searchbar-init">
      <div class="searchbar-inner">
        <div class="searchbar-input-wrap">
          <input type="search" placeholder="키워드를 검색하세요"/>
          <i class="searchbar-icon"></i>
           <span class="input-clear-button"></span>
        </div>
        <span class="searchbar-disable-button">Cancel</span>
        <input type="submit">
      </div>
    </form> -->
  </div>
</div>

<div class="page-content">
  <div class="fab fab-extended fab-right-bottom color-blue">
    <%= link_to new_post_path(picked_date: @picked_date), id: "new_post" do %>
      <i class="icon f7-icons ios-only">add</i>
      <i class="icon material-icons md-only">add</i>
    <% end %>
  </div>
  <div class="list no-hairlines-md" style="margin: 0 auto;">
    <ul>
      <%= form_for "",url: diary_search_path, method: :get do %>
      <li class="item-content item-input">
        <div class="item-inner">
          <div class="item-input-wrap">
            <%= text_field_tag :search, @search_term, placeholder:"키워드를 검색하세요" %>
            <span class="input-clear-button"></span>
          </div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>

  <%= render 'shared/inline_calendar' %>
  <div class="block">
    <div class="block-title">포스트</div>
    <div class="list media-list" id="post_div">
      <%= render 'post_list', target_posts: @target_posts %>
    </div>
  </div>
</div>

app/views/diary/new_post.html.erb
<div class="navbar no-shadow">
  <div class="navbar-inner sliding">
    <div class="left">
      <a href="#" class="link back">
        <i class="icon icon-back"></i>
        <span class="ios-only">Back</span>
      </a>
    </div>
    <div class="title">새 글 작성</div>
  </div>
</div>

<div class="page-content">
  <div class="block">
    <div class="block-title"><%= @picked_date %> 다이어리 작성</div>
    <div class="list inline-labels no-hairlines-md">
      <%= form_for @post, url: '/diary/create_post' do |f| %>
        <%= f.hidden_field :user_id,value: current_user.id %>
        <%= f.hidden_field :posted_at,value: @picked_date %>

        <!-- 옷 정보 -->
        <%= hidden_field_tag :clothes_info, value: "" %>

        <% if @post.errors.any? %>
          <div id="errorExplanation">
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
            <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <ul>
          <li class="item-content item-input">
            <div class="row" style="width:100%;">
              <div class="item-inner col">
                <div class="item-title item-label" style="font-size:0.7em;color:grey;">공개범위</div>
                <div class="item-input-wrap">
                  <%= f.select(:open_range, options_for_select([['전체공개','전체공개'], ['나만보기','나만보기']]), value:'전체공개' ) %>
                </div>
              </div>
              <div class="item-inner col">
                <div class="item-title item-label" style="font-size:0.7em;color:grey;">이벤트</div>
                <div class="item-input-wrap">
                  <%= select_tag(:event, options_for_select([['비즈니스','비즈니스'], ['데이트','데이트'], ['친구약속','친구약속'], ['데일리','데일리']]), value:'비즈니스' ) %>
                </div>
              </div>
            </div>
          </li>
          <li class="item-content item-input">
            <div class="item-inner">
              <div class="item-input-wrap">
                <img id="image_upload" src="#" />
                <!-- <input type='file' onchange="readURL(this);" /> -->
                <%= f.file_field :image %>
              </div>
            </div>
          </li>
          <li class="item-content item-input">
            <div class="item-inner">
              <div class="item-input-wrap">
                <%= f.text_field :title, placeholder:"제목" %>
                <span class="input-clear-button"></span>
              </div>
            </div>
          </li>
          <li class="item-content item-input">
            <div class="item-inner">
              <div class="item-input-wrap">
                <%= f.text_area :body, placeholder:"내용" %>
                <span class="input-clear-button"></span>
              </div>
            </div>
          </li>
          <div class="list links-list" style="margin:0 auto;" >
            <ul style="padding-left:0px;">
              <li class="item-content item-input">
                <div class="item-inner">
                  <div class="item-input-wrap">
                    <a class="link popup-open" style="padding-left:0px;" href="#" data-popup=".popup-about">Category</a>
                  </div>
                </div>
              </li>
            </ul>
          </div>
          <div class="popup popup-about">
            <div class="block">
              <a class="button button-fill color-blue link popup-close" id="category_select_btn" href="#">선택완료</a>
              <div class="block-title">Category</div>
              <div class="list accordion-list">
                <ul>
                  <% Cloth.get_clothes_info.each do |key, value| %>
                    <li class="accordion-item">
                      <a href="#" class="item-content item-link">
                        <div class="item-inner">
                          <div class="item-title"><%= key %></div>
                        </div>
                      </a>
                      <div class="accordion-item-content">
                        <div class="block">
                          <div class="list">
                            <ul>
                              <% value.each do |cloth_name| %>
                                <li>
                                  <label class="item-radio item-content">
                                    <input type="radio" name="demo-radio" value="<%= key %>_<%= cloth_name %>" /> <!-- checked="checked"/> -->
                                    <i class="icon icon-radio"></i>
                                    <div class="item-inner">
                                      <div class="item-title"><%= cloth_name %></div>
                                    </div>
                                  </label>
                                </li>
                              <% end %>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
          <li class="item-content item-input">
            <div class="item-inner">
              <div class="item-title item-label">Preference</div>
              <div class="item-input-wrap">
                <div class="range-slider range-slider-init" data-label="true">
                  <input type="range" name="preference" value="5" min="1" max="5" step="1">
                </div>
              </div>
            </div>
          </li>
          <div class="block">
            <%= f.submit class:"button button-fill color-blue" %>
          </div>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/diary/pick_date.js.erb
$('#post_div').html("<%= j(render 'post_list', target_posts: @target_posts) %>");

app/views/diary/show_post.html.erb
<%= navback "" %>

<div class="page-content">
  <div class="block">
    <div class="card demo-facebook-card">
      <div class="card-header">
        <!-- <div class="demo-facebook-avatar"><img src="http://lorempixel.com/68/68/people/1/" width="34" height="34"/></div> -->
        <div class="demo-facebook-name" style="margin-left:0px;"><%= @post.title %></div>
        <div class="demo-facebook-date" style="margin-left:0px;"><%= @post.posted_at.strftime("%Y, %m월 %d일") %></div>
      </div>
      <div class="card-content card-content-padding">
        <p><%= simple_format @post.body %></p>
        <% if @post.image.present? %>
          <%= image_tag "#{@post.image}" %>
        <% else %>
          <%= image_tag "https://placehold.it/300x300" %>
        <% end %>
        <%= link_to '수정', "/diary/edit_post/#{@post.id}" %>
        <%= link_to '삭제', "/diary/destroy_post/#{@post.id}", data: {confirm: "정말 삭제하시겠습니까?"}, method: :delete %>
      </div>
    </div>
  </div>
</div>