config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}

  #diary
  get '/diary/index_post' => 'diary#index_post', as: 'index_posts'
  get '/diary/new_post' => 'diary#new_post', as: 'new_post'
  get '/diary/show_post/:id' => 'diary#show_post', as: 'show_post'
  post '/diary/create_post' => 'diary#create_post'
  get '/diary/edit_post/:id' => 'diary#edit_post'
  patch '/diary/update_post' => 'diary#update_post'
  delete '/diary/destroy_post/:id' => 'diary#destroy_post'
  get '/diary/pick_date' => 'diary#pick_date'

  #search
  get 'diary/search' => 'search#result', as: 'diary_search'

  #recommendation
  get '/recommend/result' => 'recommend#result', as:'recommend_result'

  #my page
  get '/mypage/index' => 'mypage#index', as: 'index_mypage'
  get '/mypage/category' => 'mypage#category', as: 'category'

  #lookbook
  get '/lookbook/index' => 'lookbook#index', as: 'index_lookbook'
  get '/lookbook/like/:id' => 'lookbook#likes', as: 'like_lookbook'

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    #tab1 -> diary
    if params[:picked_date].present?
      @picked_date = params[:picked_date]
    else
      @picked_date = Date.today.strftime('%Y-%m-%d')
    end
    @my_posts = Post.index(current_user)
    @target_posts = @my_posts.where(posted_at: @picked_date)
    @others_posts = Post.where.not(user_id: current_user.id)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="navbar no-shadow">
  <div class="navbar-inner">
    <div class="left"> </div>
    <div class="title" style="margin-left:170px;">쇼옷</div>
    <div class="right">
      <%= link_to destroy_user_session_path, class:"link", method: :delete do %>
        <i class="f7-icons">logout</i>
      <% end %>
    </div>
  </div>
</div>
<div class="toolbar tabbar toolbar-bottom-md">
  <div class="toolbar-inner">
    <!-- Links have "tab-link" class instead of just "link" to switch tabs -->
    <a href="#tab-1" class="tab-link tab-link-active">캘린더</a>
    <a href="#tab-2" class="tab-link">룩북</a>
    <a href="#tab-3" class="tab-link">마이페이지</a>
  </div>
</div>
<div class="tabs">
  <!-- 캘린더, active -->
  <div class="page-content tab tab-active" id="tab-1">
    <div class="fab fab-extended fab-right-bottom color-blue">
      <%= link_to new_post_path(picked_date: @picked_date), id: "new_post" do %>
        <i class="icon f7-icons ios-only">add</i>
        <i class="icon material-icons md-only">add</i>
      <% end %>
    </div>
    <div class="list no-hairlines-md" style="margin: 0 auto;">
      <ul>
        <%= form_for "",url: diary_search_path, method: :get do %>
        <li class="item-content item-input">
          <div class="item-inner">
            <div class="item-input-wrap">
              <%= text_field_tag :search, @search_term, placeholder:"키워드를 검색하세요" %>
              <span class="input-clear-button"></span>
            </div>
          </div>
        </li>
        <% end %>
      </ul>
    </div>

    <%= render 'shared/inline_calendar' %>
    <div class="block">
      <div class="block-title">포스트</div>
      <div class="list media-list" id="post_div">
        <%= render 'diary/post_list', target_posts: @target_posts %>
      </div>
    </div>
  </div>
  <!-- 룩북 -->
  <div class="page-content tab" id="tab-2">
    <div class="toolbar tabbar">
      <div class="toolbar-inner">
        <!-- Links have "tab-link" class instead of just "link" to switch tabs -->
        <a href="#closet" class="tab-link tab-link-active">Closet</a>
        <a href="#timeline" class="tab-link">타임라인</a>
      </div>
    </div>
    <!-- Tabs -->
    <div class="tabs">
      <div class="page-content tab tab-active" id="closet" style="padding-top:0px;">
        <div class="block">
          <div class="row">
            <% if @my_posts.count == 0 %>
              <p>등록된 다이어리가 없습니다</p>
            <% else %>
              <% @my_posts.each do |p| %>
                <div class="col-50" id="image-container">
                  <%= link_to show_post_path(p.id) do %>
                    <% if p.image.present? %>
                      <%= image_tag "#{p.image}" %>
                    <% else %>
                      <%= image_tag "https://placehold.it/300x300" %>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <!-- Second tab -->
      <div class="page-content infinite-scroll-content tab" id="timeline" style="padding-top:0px;">
        <div class="block card-container">
          <% if @others_posts.count == 0 %>
            <div class="block">
              <p>다른 사람이 올린 글이 없습니다</p>
            </div>
          <% else %>
            <div id="others-lookbook">
              <%= render 'lookbook/card_item', posts: @others_posts %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- 마이페이지 -->
  <div class="page-content tab" id="tab-3">
    <div class="block">
      <div class="block-title">내 패션 모아보기</div>
      <div class="list media-list">
        <% if @my_posts.count == 0 %>
          <div class="block">
            <p>등록된 다이어리가 없습니다</p>
          </div>
        <% else %>
          <ul>
            <% @my_posts.each do |post| %>
              <li>
                <a href="#" class="item-link item-content">
                  <div class="item-media">
                    <% if post.image.present? %>
                      <img src="<%= post.image %>" width="80"/>
                    <% else %>
                      <img src="https://placehold.it/80x80" width="80"/>
                    <% end %>
                  </div>
                  <div class="item-inner">
                    <div class="item-title-row">
                      <div class="item-title"><%= post.posted_at.strftime("%Y, %m월 %d일") %></div>
                    </div>
                    <div class="item-subtitle"><%= post.title %></div>
                    <div class="item-text"><%= post.body %></div>
                  </div>
                </a>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="block">
      <div class="block-title">카테고리 정리</div>
      <div class="list links-list">
        <ul>
          <li><a href="<%= category_path %>">Category</a></li>
        </ul>
      </div>
    </div>
    <div class="block">
      <div class="block-title">추천</div>
      <div class="list links-list">
        <ul>
          <li><a href="<%= recommend_result_path %>">추천 결과보기</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="page-content">
  <div class="block">
    <div class="block-title">
      <%= link_to '캘린더', index_posts_path %>
    </div>
    <div class="block-title">
      <%= link_to '내 패션 모아보기', index_mypage_path %>
    </div>
    <div class="block-title">
      <%= link_to '룩북/타임라인 조회', index_lookbook_path %>
    </div>
    <% if user_signed_in? %>
      <%= link_to "로그아웃", destroy_user_session_path, method: :delete %>
    <% end %>
  </div>
</div>