config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}

  #diary
  get '/diary/index_post' => 'diary#index_post', as: 'index_posts'
  get '/diary/new_post' => 'diary#new_post', as: 'new_post'
  get '/diary/show_post/:id' => 'diary#show_post', as: 'show_post'
  post '/diary/create_post' => 'diary#create_post'
  get '/diary/edit_post/:id' => 'diary#edit_post'
  patch '/diary/update_post' => 'diary#update_post'
  delete '/diary/destroy_post/:id' => 'diary#destroy_post'
  get '/diary/pick_date' => 'diary#pick_date'

  #search
  get 'diary/search' => 'search#result', as: 'diary_search'

  #recommendation
  get '/recommend/result' => 'recommend#result', as:'recommend_result'

  #my page
  get '/mypage/index' => 'mypage#index', as: 'index_mypage'
  get '/mypage/category' => 'mypage#category', as: 'category'

  #lookbook
  get '/lookbook/index' => 'lookbook#index', as: 'index_lookbook'
  get '/lookbook/like/:id' => 'lookbook#likes', as: 'like_lookbook'

  root 'home#index'
end

app/controllers/lookbook_controller.rb
class LookbookController < ApplicationController
  def index
    @my_posts = Post.index(current_user)
    @others_posts = Post.where.not(user_id: current_user.id)
  end

  def likes
    likes = UserPost.find_by(user_id: current_user.id, post_id: params[:id])
    #좋아요가 눌렸는지 체크
    if likes.nil?
      UserPost.create(user_id: current_user.id, post_id: params[:id])
    else
      likes.destroy
    end
    @others_posts = Post.where.not(user_id: current_user.id)
    respond_to do |format|
      format.js { render :nothing => true }
    end
  end
end

app/helpers/lookbook_helper.rb
module LookbookHelper
end

app/views/lookbook/_card_item.html.erb
<% posts.each do |post| %>
  <div class="card demo-facebook-card">
    <div class="card-header">
      <!-- <div class="demo-facebook-avatar"><img src="http://lorempixel.com/68/68/people/1/" width="34" height="34"/></div> -->
      <div class="demo-facebook-name" style="margin-left:0px;"><%= post.title %></div>
      <div class="demo-facebook-date" style="margin-left:0px;"><%= post.posted_at.strftime("%Y, %m월 %d일") %></div>
      <div class="demo-facebook-date" style="margin-left:0px;"><%= User.find(post.user_id).email %></div>
    </div>
    <div class="card-content card-content-padding">
      <p><%= simple_format post.body %></p>
      <% if post.image.present? %>
        <%= image_tag "#{post.image}" %>
      <% else %>
        <%= image_tag "https://placehold.it/300x300" %>
      <% end %>
      <p class="likes">좋아요 <%= UserPost.where(post_id: post.id).count %></p>
    </div>
    <div class="card-footer">
      <% if UserPost.where(post_id: post.id, user_id: current_user.id).count > 0 %>
        <%= link_to "좋아요 취소", like_lookbook_path(post.id), remote: true %>
      <% else %>
        <%= link_to "좋아요", like_lookbook_path(post.id), remote: true %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/lookbook/index.html.erb
<div class="navbar no-shadow">
  <div class="navbar-inner">
    <div class="left">
      <a href="#" class="link back">
        <i class="icon icon-back"></i>
        <span class="ios-only">Back</span>
      </a>
    </div>
    <div class="title">마이페이지</div>
  </div>
</div>
<div class="toolbar tabbar">
  <div class="toolbar-inner">
    <!-- Links have "tab-link" class instead of just "link" to switch tabs -->
    <a href="#tab-1" class="tab-link tab-link-active">Closet</a>
    <a href="#tab-2" class="tab-link">타임라인</a>
  </div>
</div>
<!-- Tabs -->
<div class="tabs">
  <div class="page-content tab tab-active" id="tab-1">
    <div class="block">
      <div class="row">
        <% @my_posts.each do |p| %>
          <div class="col-50" id="image-container">
            <%= link_to show_post_path(p.id) do %>
              <% if p.image.present? %>
                <%= image_tag "#{p.image}" %>
              <% else %>
                <%= image_tag "https://placehold.it/300x300" %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <!-- Second tab -->
  <div class="page-content infinite-scroll-content tab" id="tab-2">
    <div class="block card-container">
      <% if @others_posts.count == 0 %>
        <div class="block">
          <p>다른 사람이 올린 글이 없습니다</p>
        </div>
      <% else %>
        <% @others_posts.each do |p| %>
          <%= render 'card_item' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/lookbook/likes.js.erb
$$('#others-lookbook').html("<%= j(render 'lookbook/card_item', posts: @others_posts) %>");